// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal.proto

It has these top-level messages:
	User
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	ID            int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	Username      string `protobuf:"bytes,3,opt,name=Username" json:"Username,omitempty"`
	Role          string `protobuf:"bytes,4,opt,name=Role" json:"Role,omitempty"`
	Password      string `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
	Email         string `protobuf:"bytes,6,opt,name=Email" json:"Email,omitempty"`
	Expiry        int64  `protobuf:"varint,7,opt,name=Expiry" json:"Expiry,omitempty"`
	Amount        string `protobuf:"bytes,8,opt,name=Amount" json:"Amount,omitempty"`
	Bank          string `protobuf:"bytes,9,opt,name=Bank" json:"Bank,omitempty"`
	BuyStatus     string `protobuf:"bytes,10,opt,name=BuyStatus" json:"BuyStatus,omitempty"`
	SellStatus    string `protobuf:"bytes,11,opt,name=SellStatus" json:"SellStatus,omitempty"`
	WalletAddress string `protobuf:"bytes,12,opt,name=WalletAddress" json:"WalletAddress,omitempty"`
	Authenticated bool   `protobuf:"varint,13,opt,name=Authenticated" json:"Authenticated,omitempty"`
	ImageURL      string `protobuf:"bytes,14,opt,name=ImageURL" json:"ImageURL,omitempty"`
	CreatedTime   int64  `protobuf:"varint,15,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	Firstname     string `protobuf:"bytes,16,opt,name=Firstname" json:"Firstname,omitempty"`
	Lastname      string `protobuf:"bytes,17,opt,name=Lastname" json:"Lastname,omitempty"`
	Url           string `protobuf:"bytes,18,opt,name=Url" json:"Url,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *User) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *User) GetBank() string {
	if m != nil {
		return m.Bank
	}
	return ""
}

func (m *User) GetBuyStatus() string {
	if m != nil {
		return m.BuyStatus
	}
	return ""
}

func (m *User) GetSellStatus() string {
	if m != nil {
		return m.SellStatus
	}
	return ""
}

func (m *User) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *User) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *User) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *User) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "internal.User")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x53, 0x0a, 0x58, 0x06, 0x41, 0xdc, 0x18, 0x33, 0x31, 0xc6, 0x34, 0xc6, 0x03, 0x27,
	0x2f, 0xfe, 0x02, 0x10, 0x4c, 0x48, 0x38, 0x98, 0x02, 0xf1, 0xbc, 0xda, 0x89, 0x36, 0x6c, 0x5b,
	0xb2, 0xbb, 0x8d, 0xf2, 0x87, 0xfd, 0x1d, 0x66, 0x67, 0x5b, 0x84, 0xdb, 0xbc, 0xef, 0xbd, 0xcc,
	0xf4, 0x75, 0x61, 0x98, 0x15, 0x96, 0x74, 0x21, 0xd5, 0xe3, 0x4e, 0x97, 0xb6, 0x14, 0x51, 0xa3,
	0xef, 0x7f, 0x43, 0x68, 0x6f, 0x0c, 0x69, 0x31, 0x84, 0xd6, 0x62, 0x86, 0x41, 0x1c, 0x8c, 0xc3,
	0xa4, 0xb5, 0x98, 0x89, 0x2b, 0xe8, 0xac, 0xcb, 0x2d, 0x15, 0xd8, 0x8a, 0x83, 0x71, 0x2f, 0xf1,
	0x42, 0xdc, 0x40, 0xe4, 0xd2, 0x85, 0xcc, 0x09, 0x43, 0x36, 0x0e, 0x5a, 0x08, 0x68, 0x27, 0xa5,
	0x22, 0x6c, 0x33, 0xe7, 0xd9, 0xe5, 0x5f, 0xa5, 0x31, 0xdf, 0xa5, 0x4e, 0xb1, 0xe3, 0xf3, 0x8d,
	0x76, 0x17, 0xe6, 0xb9, 0xcc, 0x14, 0x76, 0xfd, 0x05, 0x16, 0xe2, 0x1a, 0xba, 0xf3, 0x9f, 0x5d,
	0xa6, 0xf7, 0x78, 0xc6, 0xdf, 0x52, 0x2b, 0xc7, 0x27, 0x79, 0x59, 0x15, 0x16, 0x23, 0x8e, 0xd7,
	0xca, 0x5d, 0x9d, 0xca, 0x62, 0x8b, 0x3d, 0x7f, 0xd5, 0xcd, 0xe2, 0x16, 0x7a, 0xd3, 0x6a, 0xbf,
	0xb2, 0xd2, 0x56, 0x06, 0x81, 0x8d, 0x7f, 0x20, 0xee, 0x00, 0x56, 0xa4, 0x54, 0x6d, 0xf7, 0xd9,
	0x3e, 0x22, 0xe2, 0x01, 0x06, 0x6f, 0x52, 0x29, 0xb2, 0x93, 0x34, 0xd5, 0x64, 0x0c, 0x9e, 0x73,
	0xe4, 0x14, 0xba, 0xd4, 0xa4, 0xb2, 0x5f, 0x54, 0xd8, 0xec, 0x43, 0x5a, 0x4a, 0x71, 0x10, 0x07,
	0xe3, 0x28, 0x39, 0x85, 0xae, 0xff, 0x22, 0x97, 0x9f, 0xb4, 0x49, 0x96, 0x38, 0xf4, 0xfd, 0x1b,
	0x2d, 0x62, 0xe8, 0x3f, 0x6b, 0x72, 0xb1, 0x75, 0x96, 0x13, 0x5e, 0x70, 0xdd, 0x63, 0xe4, 0x7a,
	0xbc, 0x64, 0xda, 0x58, 0xfe, 0xdd, 0x23, 0xdf, 0xe3, 0x00, 0xdc, 0xee, 0xa5, 0xac, 0xcd, 0x4b,
	0xbf, 0xbb, 0xd1, 0x62, 0x04, 0xe1, 0x46, 0x2b, 0x14, 0x8c, 0xdd, 0xf8, 0xde, 0xe5, 0x97, 0x7f,
	0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xec, 0xd5, 0x18, 0x8b, 0x0b, 0x02, 0x00, 0x00,
}
